# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
matrix:
  allow_failures:
    - julia: nightly
  exclude:
    - os: osx
      arch: x86
julia:
  - 1.0
  - 1.3
  - nightly
notifications:
  email: false

# push coverage results to Codecov
after_success:
  - julia -e 'cd(Pkg.dir("ObjectFile")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
